export type ThemeVariationPrompts = readonly [string, string, string, string];

export const THEME_VARIATION_PROMPTS: Partial<Record<string, ThemeVariationPrompts>> = {
  "golden-hour-beach": [
    "Wide shoreline walk: selected cast barefoot on wet reflective sand, full bodies visible, staggered naturally, one person glancing back, ocean horizon clean and low.",
    "Seated dunes portrait: selected cast nestled shoulder-to-shoulder on a blanket near sea oats, knee-up crop, grasses framing the foreground, warm rim light through the dunes.",
    "Low waterline candid: selected cast at the retreating tide with small splashes and rolled cuffs, laughter caught mid-motion, lower camera near the sand, beach stretching behind.",
    "Tight wind portrait: waist-up or shoulder-up grouping with wind in hair and linen, sunset glow behind shoulders, soft negative space of sky and sea.",
  ],
  "autumn-cabin": [
    "Cabin-steps welcome: family gathered on wooden porch steps with mugs and knit layers, breath visible, pumpkins and boots nearby.",
    "Woodpile candid: family near stacked firewood, one subject adjusting a scarf, leaves drifting through crisp morning light.",
    "Trail-return moment: family walking back toward the cabin along a leaf-strewn path, casual spacing and warm hand gestures.",
    "Window-glow portrait: tighter grouping beside the cabin window with amber interior light, blankets wrapped around shoulders.",
  ],
  "kinfolk-kitchen": [
    "Table-prep frame: family around a flour-dusted table, hands arranging ingredients, one subject leaning in with a small laugh.",
    "Sink-window portrait: family gathered near the kitchen window, herb pots and ceramic mugs visible, quiet editorial stillness.",
    "Shared-platter candid: family passing a wooden board or bowl across the table, overlapping hands and natural eye contact.",
    "Doorway crop: tighter vertical-feeling composition through a kitchen doorway, linen textures, soft side light and calm expressions.",
  ],
  "vintage-polaroid": [
    "Couch-squeeze snapshot: family packed close on the living-room couch, flash-lit faces, one person slightly cropped by the Polaroid edge.",
    "Kitchen-counter snapshot: family leaning around a laminate counter with mugs or snacks, off-level framing and casual mid-laugh timing.",
    "Hallway-flash frame: family clustered in a narrow hallway or doorway, direct flash, red-eye-era imperfection, warm paneling behind.",
    "Floor-level candid: family sitting on carpet around scattered albums or toys, low awkward camera angle, one subject blurred by motion.",
  ],
  "leibovitz-studio": [
    "Classical seated tableau: family arranged around one seated anchor subject, painterly triangular composition and controlled gestures.",
    "Standing editorial frame: staggered standing group with tailored silhouettes, one subject slightly turned away, dramatic side light.",
    "Close intimate crop: shoulder-to-shoulder grouping, faces layered in depth, quiet unscripted glances under Rembrandt light.",
    "Wide set portrait: family placed within the painted studio backdrop, polished floor visible, refined magazine-cover negative space.",
  ],
  "stacked-love": [
    "Tiered pyramid close-up: selected people arranged in a gentle vertical stack, taller subjects slightly higher, shorter subjects lower, faces close and smiling on a clean white backdrop.",
    "Horizontal cheek line: selected people nestled in a tight shoulder-up row across the frame, heads nearly level, cheeks and shoulders overlapping, warm eye contact and monochrome studio softness.",
    "Graphic album-cover portrait: selected people clustered asymmetrically in the lower third or one side of the frame, diagonal face spacing, relaxed smiles and large clean white negative space.",
    "Seated studio pile: one adult seated as the anchor, children leaning naturally against shoulders, second adult tucked behind or beside them, waist-up crop with relaxed visible hands.",
  ],
  "pop-icon-stage-portrait": [
    "Text-free premium social teaser: selected cast standing full-body on a dramatic concert stage, King of Pop Stage Portrait vibe, one adult in a vivid red military-style performance jacket with gold accents, black cropped pants, bright white socks and black loafers; another cast member in a black fedora-inspired hat; kids in coordinated sparkling black-and-white outfits, joyful confident poses.",
    "Low stage hero frame: selected cast staggered in a vertical concert-poster composition with IP-safe 1980s pop superstar stage energy, glittering spotlights, cinematic smoke, moonlit glossy floor reflections, no celebrity likeness, no names, no logos.",
    "Tight performance-family crop: selected cast shoulder-to-knee with sharp black-white-silver tailoring, sequined highlights, optional sunglasses or sparkling accessories where natural, theatrical smiles, deep blue-black shadows and bright follow-spot edges.",
    "Encore tableau: selected cast arranged like a polished tour-photo finale on a smoky stage, dramatic hand poses, black-and-white performance styling with one red jacket accent, bright overhead beams, premium editorial quality, no text or watermark.",
  ],
  "galactic-family-adventure": [
    "Hangar doorway hero: selected cast full-body in layered desert-traveler robes inside a sci-fi hangar arch, warm twin-sun horizon behind, pet clearly grounded when selected.",
    "Guardian silhouette frame: selected cast grouped in front of a tall original armored guardian figure, glowing blue practical panels, heroic vertical composition and readable faces.",
    "Desert-world expedition: selected cast standing with capes, scarves and utility belts, distant ships and spires in haze, bronze sunset rim light, no franchise symbols or glowing weapons.",
    "Family crew portrait: selected cast arranged as an original space-adventure crew with one seated or kneeling child/pet anchor, cool hangar fill and warm backlight balanced for print.",
  ],
  "iconic-crosswalk-album-cover": [
    "Straight crosswalk walk: selected cast walking left-to-right across a zebra crosswalk in a side-oriented cinematic walk, mostly side-facing bodies with slight natural face turns toward camera for readable faces, evenly spaced one behind another, stylish coats and boots, soft overcast city light, vertical album-cover framing.",
    "Classic crossing frame: selected cast mid-stride on bold white crosswalk stripes, bodies mostly visible with readable faces, one subject slightly ahead but still in a clean horizontal procession, quiet London-like street and soft architecture behind.",
    "Symmetric street-cover composition: selected cast crossing from curb to curb with legs in motion, clean zebra-crossing geometry filling the foreground, balanced negative space above, muted coats, polished shoes and natural calm expressions.",
    "Music-magazine walking portrait: selected cast in a deliberate side-oriented street-crossing line, mostly side-facing with slight natural face turns for readable faces, not standing still, not facing camera as a posed group, no sidewalk pose, subtle film grain and no band likeness.",
  ],
  "runway-editor-in-chief-family-editorial": [
    "Glass-tower office portrait: selected cast in camel, ivory, charcoal and black tailoring, one seated anchor, reflective marble floor, city windows and glossy magazine light.",
    "Runway-family stance: selected cast staggered like a high-fashion cover shoot, confident posture, sharp lapels, controlled hands, polished neutral palette and no visible logos.",
    "Executive lounge crop: selected cast knee-up around a leather chair or sleek sofa, pet posed in foreground when selected, crisp cheek highlights and premium retouch.",
    "Editorial corridor frame: selected cast walking or standing in a modern city-office corridor, tall vertical lines, glossy black accents and calm luxury styling.",
  ],
  "noughties-family-throwback": [
    "Ball-pit flash candid: selected cast laughing in a colorful indoor ball pit, warm compact-camera flash, slightly off-center vertical snapshot, playful motion but clear faces.",
    "Mall-party portrait: selected cast clustered in a bright early-2000s play-zone or mall-photo setting, denim layers, primary colors and polished nostalgic flash.",
    "Sticker-album family frame: selected cast close together with casual striped tops, hoodies or denim, direct flash, cheerful clutter and premium print-ready color.",
    "Low playful crop: selected cast partially surrounded by colorful plastic balls or party props, one subject cropped candidly, warm JPEG-era color character and natural smiles.",
  ],
  "dockside-family-weekend": [
    "End-of-dock portrait: selected cast gathered near the lake edge on weathered planks, folded towels and canvas tote nearby, waterline low and faces warmly rim-lit.",
    "Boat-cushion candid: selected cast seated or leaning around simple boat cushions and dock cleats, relaxed weekend gestures, lake house and pines softened behind.",
    "Shoreline walk proof: selected cast walking along the dock toward camera, striped towels over shoulders, safe rail or shoreline context visible, full bodies when natural.",
    "Tight lake-glow crop: waist-up grouping with sparkling water bokeh behind, breezy hair, sun-faded summer color and clear subject separation.",
  ],
  "backyard-sports-day-portrait": [
    "Relay-lane hero: selected cast in blank athletic tops at chalk lane marks, one ribbon marker or baton prop, joyful motion with readable faces and no team branding.",
    "Trophy-ribbon portrait: selected cast clustered around simple ribbons and lawn-game props, funny-proud expressions, grass field and cones framing the foreground.",
    "Low sideline action: selected cast mid-game on backyard grass, sneakers and hands visible, bright open-shade sports-lifestyle polish and no sponsor marks.",
    "Team-photo field day: selected cast arranged like a friendly family squad portrait in blank jerseys, chalkboard-free background, cones and ribbon markers only.",
  ],
  "slow-travel-summer-picnic": [
    "Market-blanket scene: selected cast seated around a checked blanket with fruit, basket and paper maps, meadow or village view behind, relaxed hands and smiles.",
    "Canal-path picnic: selected cast near a quiet towpath or overlook, blanket edge in foreground, wildflowers and travel bag details, slow afternoon light.",
    "Passing-fruit candid: selected cast sharing berries or bread on the blanket, overlapping hands, natural laughter and warm travel-photo grain.",
    "Wide postcard meadow: selected cast smaller in a scenic summer field with blanket and basket visible, plenty of sky and landscape, calm editorial spacing.",
  ],
  "sunset-festival-family-glow": [
    "Lantern-lane portrait: selected cast standing under paper lanterns and string lights at sunset, soft crowd-free bokeh, coral and teal fabric flags framing faces.",
    "Food-stall glow candid: selected cast near simple family-friendly stall shapes, warm lantern light, safe snack props, no alcohol cues and no readable signs.",
    "Festival-close sparkle: waist-up selected-cast grouping with tasteful face-safe sparkle and warm golden rim light, glowing lights behind and clean subject separation.",
    "Wide evening fairway: selected cast walking through a quiet festival lane, flags and lights overhead, sunset sky visible, joyful print-ready color without performer likeness.",
  ],
  "summer-color-pop-studio": [
    "Color-block lineup: selected cast full-to-three-quarter body on a seamless studio floor, turquoise, red and yellow panels behind, glossy props spaced cleanly.",
    "Beach-ball campaign crop: selected cast shoulder-to-knee with beach-ball shapes and striped mats, bright commercial smiles, crisp catchlights and no text.",
    "Graphic staggered pose: selected cast spread across the white cyclorama with bold summer color blocks, visible hands and stable contact shadows.",
    "Tight pop portrait: selected cast clustered against saturated color panels, sunglasses as simple props where natural, polished skin texture and clean white margins.",
  ],
  "whimsical-adventure-postcard": [
    "Station-platform postcard: selected cast beside oversized luggage on a tiny illustrated platform, rolling hills behind, decorative blank border and no readable text.",
    "Map-edge overlook: selected cast at a scenic storybook overlook with painted map-edge shapes framing the corners, warm sky wash and clear faces.",
    "Adventure-procession proof: selected cast walking along a curved path with bags and flags, playful silhouettes, gouache texture and original non-franchise charm.",
    "Close painted keepsake: selected cast waist-up within a whimsical postcard frame, clouds and hills behind, warm paper texture and cheerful color separation.",
  ],
  "retro-summer-postcard": [
    "Beach-postcard portrait: selected cast grouped on warm sand with striped towels and linen layers, clean horizon, rose-warm film color and generous print margins.",
    "Lake-picnic keepsake: selected cast seated near a summer blanket with fruit and sun-faded fabric, relaxed faces, water or grass context behind.",
    "Vacation-walk candid: selected cast walking through late-afternoon summer light with retro stripes and casual linen, postcard-balanced spacing and soft film grain.",
    "Tight sun-wash crop: waist-up selected-cast grouping against sky blue and cream background, mild rosy highlights, clear faces and no app-filter artifacts.",
  ],
  "toy-box-keepsake-portrait": [
    "Block-floor portrait: selected cast gathered on a soft rug among generic wooden blocks, picture books and handmade keepsakes, low seated-level camera and bright window light.",
    "Storybook-shelf frame: selected cast near tidy cubbies and a reading nook, soft primary colors, relaxed parent-child gestures and clean face readability.",
    "Toy-box candid: selected cast reaching toward simple handmade toys and open storybooks, playful floor-level composition, uncluttered nursery texture.",
    "Keepsake close portrait: selected cast shoulder-to-knee with maple wood, pastel rugs and blank book spines behind, warm smiles and polished keepsake finish.",
  ],
  "cool-blue-lake-day": [
    "End-of-dock blue portrait: selected cast on weathered planks with still lake water behind, pale denim and linen styling, crisp cool morning light.",
    "Shoreline breeze frame: selected cast standing near reeds or a coastal overlook, glacier-blue accents, airy negative space and modest summer layers.",
    "Lake-blanket candid: selected cast seated beside simple towels and picnic details, dewy highlights, water-bounced fill and calm editorial freshness.",
    "Tight blue-hour crop: waist-up selected-cast grouping with cool water bokeh, cloud cream wardrobe notes, clean faces and premium print contrast.",
  ],
  "poetcore-family-library-portrait": [
    "Reading-chair portrait: selected cast gathered around a worn reading chair with books and blank cards nearby, oversized knits and warm window light.",
    "Writing-desk candid: selected cast leaning near a wooden desk with stationery details, vintage blazers, soft lamp glow and intimate study-room depth.",
    "Library-aisle frame: selected cast standing between shelves with book stacks secondary, messenger satchel texture and quiet literary editorial mood.",
    "Close letter-card crop: selected cast waist-up beside parchment-toned cards and shelves, wool and tweed details, soft amber falloff and clear faces.",
  ],
  "butter-yellow-summer-portrait": [
    "Porch-linen portrait: selected cast gathered on a sunny porch with butter-yellow accents, pale florals and white linen, airy late-morning light and readable faces.",
    "Garden-path candid: selected cast walking through soft greenery with woven basket details, yellow wardrobe notes secondary, natural hands and crisp summer polish.",
    "Coastal-cottage frame: selected cast near hydrangeas or a pale cottage wall, warm cream palette, relaxed editorial spacing and no visible branding.",
    "Tight butter-yellow crop: waist-up selected-cast grouping against bright floral and linen texture, creamy bounce fill, natural skin detail and clean background.",
  ],
  "scarf-garden-story": [
    "Scarf-path portrait: selected cast on a leafy garden path with silk-scarf color accents, dappled light and faces held in the clear center third.",
    "Garden-table candid: selected cast leaning around a simple outdoor table with scarf fabric and flowers secondary, warm open shade and refined summer mood.",
    "Climbing-greenery frame: selected cast standing near trellis leaves and soft blossoms, scarf details moving lightly, vertical editorial composition and no logos.",
    "Close scarf-color crop: waist-up selected-cast grouping with sage, red and pale yellow fabric accents, romantic garden bokeh and crisp subject separation.",
  ],
  "summer-color-hunt": [
    "Swatch-garden portrait: selected cast arranged near simple color swatches, flowers and fruit bowls, props secondary and no readable labels.",
    "Color-search candid: selected cast reaching toward bright garden color clusters, active lifestyle framing, cheerful open-shade light and clean faces.",
    "Backyard discovery frame: selected cast in a tidy backyard color-hunt setup with red, blue, yellow and green accents, no boards or logos.",
    "Tight color-pop crop: selected cast waist-up against flowers and fruit color blocks, crisp catchlights and polished summer lifestyle finish.",
  ],
  "family-watch-party": [
    "Sofa watch-party portrait: selected cast grouped on a cozy sofa with blank pennants, snack bowls and pillows, warm lamp glow and no screen content.",
    "Game-day snack candid: selected cast leaning around a tidy coffee table, color-block decor and soft TV-like fill, no scoreboards or team marks.",
    "Blank-banner living room: selected cast framed beneath plain banners and blankets, layered sofa geometry, energetic expressions and no readable text.",
    "Close cheering crop: waist-up selected-cast grouping with cozy pillows and soft blue-warm mixed light, family-safe excitement and clean subject separation.",
  ],
  "ocean-explorer-card": [
    "Tide-pool card proof: selected cast grouped beside tide pools and shells with open sky reserved for greeting text, sea-glass palette and clean faces.",
    "Map-edge shoreline: selected cast framed by decorative paper-map edges and compass-like shapes, no readable map text and airy card margin.",
    "Shell-path adventure: selected cast walking along a calm shoreline with shells and sand details, bright coastal light and safe shallow-water context.",
    "Close explorer card crop: selected cast waist-up against pale sand and blue water, coral accents, typography space held clear and no resort logos.",
  ],
  "time-travel-toy-shelf": [
    "Shelf-world portrait: selected cast framed among handmade wooden toys and blank book spines, warm dust-mote light and miniature keepsake scale.",
    "Toy-era vignette: selected cast near tiny generic time-capsule objects, paper stars and blocks, clear faces and no branded character shapes.",
    "Low shelf adventure: selected cast walking or sitting along shelf levels with soft primary colors, tactile handmade texture and decorative blank labels.",
    "Close toy-shelf crop: waist-up selected-cast grouping between maple wood toys and faded paper details, cozy amber fill and storybook miniature charm.",
  ],
  "retro-jazz-porch": [
    "Porch-radio portrait: selected cast gathered near a vintage-style radio and woven chairs, late-afternoon shade, brass accents and no performer references.",
    "Stoop rhythm candid: selected cast relaxed on a backyard stoop with potted plants and striped shade, warm film grain and clear faces.",
    "Blank-record-sleeve frame: selected cast beside decorative blank record sleeves and porch plants, music props secondary and no readable album art.",
    "Close porch-jazz crop: waist-up selected-cast grouping with olive, rust and cream tones, soft amber side light and cozy musical mood.",
  ],
  "neo-deco-celebration-card": [
    "Arch-side greeting card: selected cast placed low-right beneath geometric arches, cream-black-gold palette, brass glints and clean greeting space upper-left.",
    "Emerald accent portrait: selected cast in tasteful evening attire near chrome and emerald details, polished floor reflection and balanced card typography area.",
    "Tomato accent celebration: selected cast arranged in a refined vertical card layout with tomato red accent decor, controlled sparkle and readable faces.",
    "Wide deco card proof: selected cast smaller within symmetrical arch geometry, elegant negative space for greeting text and no venue signage.",
  ],
  "crochet-raffia-picnic-card": [
    "Gingham greeting card: selected cast seated near a gingham blanket edge with crochet texture accents, raffia basket detail and clean greeting space in sunlit grass.",
    "Citrus picnic portrait: selected cast grouped beside fruit, flowers and cream textiles, citrus yellow and tomato accents, airy card margin on one side.",
    "Raffia hat candid: selected cast leaning into a soft picnic moment with woven details and open-shade face fill, greeting area held in pale background.",
    "Wide summer card proof: selected cast smaller on the blanket within a meadow or garden, crochet and raffia textures visible, clear typography space above.",
  ],
  "private-jet-family": [
    "Cabin lounge editorial: selected cast arranged across cream leather seats inside the private jet, polished wood trim and oval windows visible, faces readable in soft daylight.",
    "Aisle arrival portrait: selected cast standing or leaning along the jet aisle with premium luggage nearby, staggered warm poses, no visible brand logos or airline marks.",
    "Window-glow close crop: selected cast grouped near glowing cabin windows above the clouds, glossy leather highlights, relaxed luxury-travel expressions and clear faces.",
    "Wide cabin proof: selected cast smaller in the private jet interior with seating, table details and sky outside included, elegant magazine composition and no readable text.",
  ],
  "soccer-team-family": [
    "Pre-game squad photo: selected cast posed on the pitch like a professional team lineup, matching blank jerseys, cleats, one classic soccer ball and stadium lights behind.",
    "Low tunnel-to-field hero: selected cast stepping from a stadium tunnel onto green turf, cool floodlights and mist, full bodies visible and no club crests or sponsors.",
    "Captain huddle portrait: selected cast clustered around one soccer ball at center, serious game faces softening into family warmth, muddy boots and crisp rim light.",
    "Touchline poster proof: selected cast arranged near the sideline with stadium seats blurred behind, strong horizontal geometry, blank kit details and realistic sports-photo polish.",
  ],
  "white-cyclorama-exaggerated-faces": [
    "Expression lineup proof: selected cast standing full-to-three-quarter body on the seamless white cyclorama, each person making a different exaggerated expression, crisp studio spacing.",
    "Campaign close crop: selected cast shoulder-to-knee with bold faces, graphic white negative space, glossy catchlights and fashion-campaign light.",
    "Playful staggered pose: selected cast spread across the white floor curve with varied body language, clean contact shadows and no props fighting the faces.",
    "High-key group burst: selected cast caught mid-gesture in a bright studio frame, expressive faces first, clean backdrop, polished commercial retouch without plastic skin.",
  ],
  "zero-gravity-family": [
    "Floating module portrait: selected cast suspended naturally inside a bright space-station room, Earth visible through a round window, hair and socks drifting in microgravity.",
    "Window orbit close-up: selected cast gathered near the Earth-facing window with toys and snacks floating around them, readable faces and cool cabin fill.",
    "Wide station proof: selected cast smaller within curved white station architecture, floating objects showing zero gravity, clean family-friendly near-future details and no logos.",
    "Playful mid-room drift: selected cast rotating gently around the frame with relaxed expressions, soft blue rim light, visible hands and feet, believable cinematic space photography.",
  ],
  "western-wanted-family": [
    "Text-free wanted poster proof: selected cast front-facing on aged sepia parchment with western ornament areas left decorative and unreadable, cowboy hats and funny-serious outlaw faces.",
    "Saloon doorway portrait: selected cast posed in dusty coats near worn wood and warm saloon-window light, antique studio falloff and no emphasized weapons.",
    "Stacked outlaw hierarchy: selected cast arranged in a vertical poster composition with weathered paper edges, sepia ink texture and blank decorative typography bands.",
    "Close parchment character crop: selected cast waist-up with humorous serious expressions, smoky amber fill, distressed lithograph texture and no readable real text.",
  ],
  "fluffy-cloud-family": [
    "Cloud-top sunrise portrait: selected cast seated or standing on a giant soft cloud, blue-pink horizon behind, pajamas and robes moving in gentle wind.",
    "Low floating hero frame: selected cast photographed from a slightly low airy perspective with glowing cloud bounce, readable faces and generous pastel sky.",
    "Cozy cloud close-up: selected cast nestled together on the cloud surface, sunrise rim light on hair, peaceful expressions and dreamlike photoreal polish.",
    "Wide sky proof: selected cast smaller against a soft pastel sky with the full cloud shape visible, blush, cream and gold palette, no angel or religious iconography.",
  ],
  "cereal-box-family": [
    "Front-box mascot proof: selected cast illustrated as cheerful breakfast mascots on a giant cereal package, blank made-up brand panels and no readable real text.",
    "Spoon-and-rings action: selected cast centered amid oversized spoons, flying cereal rings and milk splash shapes, bold supermarket packaging energy and clean silhouettes.",
    "Glossy product close-up: selected cast waist-up on the box art with shiny print texture, saturated breakfast colors, playful expressions and no real cereal logos.",
    "Shelf-ready packaging frame: selected cast in a full vertical package composition with decorative unreadable label areas, dynamic diagonal cereal motion and polished 3D depth.",
  ],
  "wes-anderson": [
    "Standing lineup proof: selected subject or cast standing full-body on the centered patterned rug, hands empty at sides, serious deadpan expression, perfectly symmetrical furniture around them.",
    "Seated tableau proof: selected subject or cast seated formally on a couch or bench, holding a single tiny teacup or flower stem, exact pastel order and balanced side tables.",
    "Doorway grid proof: selected subject or cast standing rigidly inside nested rectangular doorways or wall panels, no handheld prop, dollhouse precision.",
    "Wide room proof: selected subject or cast placed small in a wider symmetrical room, full rug and centered furniture visible, hands folded or at sides, no book.",
  ],
  "christmas-morning": [
    "Tree-side floor candid: family clustered on the rug beside the glowing tree, wrapping paper in foreground, cocoa mugs in hand.",
    "Couch-and-stockings frame: family squeezed on the couch under stockings and garland, one subject mid-laugh over an opened gift.",
    "Morning-window portrait: tighter warm pajama grouping with tree bokeh behind and cool window fill from one side.",
    "Present-opening action: family leaning into a shared present reveal, hands overlapping, ribbon and paper creating lively foreground.",
  ],
  "card-christmas": [
    "Front-step hero card: selected cast on the porch steps beside the wreath, clean negative space on the left for greeting text.",
    "Doorway glow card: selected cast gathered in the open doorway, warm interior light behind, snow and pines framing the edges.",
    "Porch-rail candid card: selected cast leaning naturally along the porch rail, one subject mid-laugh when more than one is selected, greeting space in snowy sky.",
    "Tighter wreath portrait: waist-up grouping beside the lit wreath, elegant holiday wardrobe, calm serif-card negative space.",
  ],
  "national-geographic": [
    "Ridge-pause frame: family silhouetted against layered mountains, one adjusting a pack strap, strong documentary spacing.",
    "Trail-movement frame: family walking single-file across scree or tundra, wind shaping clothing, vast valley opening beside them.",
    "Map-check candid: family gathered around a folded map or thermos on the ridge, real weather and practical gestures.",
    "Wide awe portrait: family small against the dawn landscape, placed on the right third with dramatic sky and mist.",
  ],
  "film-noir": [
    "Desk-side mystery: family grouped around a heavy desk, one subject holding a sealed letter, venetian shadows cutting across faces.",
    "Window-silhouette frame: family near the blinds with hard backlight, elegant profiles and protective body language.",
    "Doorway noir tableau: staggered figures in a dim office doorway, one glancing over a shoulder, deep negative shadow.",
    "Close silver portrait: tight dramatic grouping with faces emerging from black, silk highlights and a single practical lamp.",
  ],
  "tuscan-summer": [
    "Long-table lunch: family gathered at a rustic outdoor table, linen, fruit and glasses catching hot afternoon light.",
    "Villa-walk frame: family walking along a cypress-lined path, relaxed spacing, terracotta walls and olive trees behind.",
    "Courtyard portrait: family in a shaded stone courtyard, one leaning on a chair, sun patches across the ground.",
    "Vineyard-wide frame: family placed against rolling vines and hills, golden haze and breezy summer wardrobe.",
  ],
  "cherry-blossom": [
    "Petal-path stroll: family walking slowly beneath blossoms, one subject looking up, petals crossing foreground.",
    "Bench portrait: family gathered near a garden bench, pastel canopy overhead, soft calm expressions.",
    "Bridge-frame candid: family paused on a small garden bridge, blossoms reflected below, asymmetric composition.",
    "Close blossom crop: tighter portrait with branches framing faces, delicate petals and airy negative space.",
  ],
  "snowy-hygge": [
    "Window-nook portrait: family wrapped in knits near a glowing window, snow falling outside, mugs and blankets visible.",
    "Cabin-floor candid: family seated around a low table or rug, warm lamplight and soft winter clutter.",
    "Doorway snow frame: family just inside the open cabin door, cool snow outside and warm interior spill behind them.",
    "Firelight close-up: tighter grouping near the hearth, faces warmed by flame, soft shadows and cozy textures.",
  ],
  "desert-santa-fe": [
    "Adobe-wall portrait: family arranged against sun-warmed adobe, turquoise and woven textures, sculptural shadows.",
    "Courtyard candid: family gathered around a tiled courtyard table, one passing a cup, desert plants framing edges.",
    "Wide mesa frame: family placed before distant desert mesas, low sun and long shadows across sand.",
    "Doorway textile crop: tighter composition in a carved doorway with rugs and pottery as rich foreground detail.",
  ],
  "parisian-cafe": [
    "Cafe-table candid: family around a small sidewalk table, cups and pastries, one subject mid-laugh.",
    "Awning portrait: family standing beneath striped awning, street reflections and wrought-iron detail behind.",
    "Window-seat frame: tighter grouping by a cafe window, warm interior glow and soft Paris street bokeh.",
    "Crosswalk lifestyle: family walking past the cafe frontage, motion in coats and scarves, cinematic street rhythm.",
  ],
  "new-york-city": [
    "Brownstone-step portrait: family on stoop steps, city texture behind, relaxed stacked composition.",
    "Crosswalk motion frame: family mid-stride across a quiet street, taxis and architecture softened in background.",
    "Corner-deli candid: family gathered near a neighborhood storefront, one subject turning back toward camera.",
    "Rooftop skyline portrait: family placed against distant skyline, wind and evening light shaping silhouettes.",
  ],
  "paris-family-stroll": [
    "Morning-walk frame: family walking along a limestone street, Eiffel Tower large but soft in background.",
    "Bridge pause: family leaning lightly along a Paris bridge rail, soft river light and elegant negative space.",
    "Cafe-corner pass: family passing a cafe corner with motion in coats, editorial travel framing.",
    "Tighter tower portrait: waist-up grouping with warm morning rim light and landmark geometry behind.",
  ],
  "backyard-picnic": [
    "Blanket-circle candid: family seated in a loose picnic circle, food in foreground and laughter crossing the blanket.",
    "Tree-shade portrait: family arranged under dappled leaves, lemonade glasses catching highlights.",
    "Serving moment: family passing strawberries or sandwiches, overlapping hands and relaxed expressions.",
    "Wide backyard frame: family small within garden beds, fence and soft flowers, sunny lifestyle atmosphere.",
  ],
  "sunday-sofa": [
    "Couch-squeeze frame: family tucked into blankets on the sofa, rain-lit window behind, book or mugs nearby.",
    "Window-light portrait: tighter grouping near the window with soft gray light and calm eye contact.",
    "Floor-and-sofa candid: some seated on the rug, some on the couch, lived-in Sunday clutter around them.",
    "Over-shoulder quiet frame: one subject reading or reaching across, family layered in soft domestic depth.",
  ],
  "orchard-picking": [
    "Ladder-and-baskets frame: family beneath fruit trees with baskets, one reaching upward, sun through leaves.",
    "Row-walk candid: family walking between orchard rows, staggered spacing and late-season color.",
    "Harvest-table portrait: family gathered around baskets on a rustic table, fruit in foreground.",
    "Wide orchard view: family framed by repeating tree rows, warm rural light and playful motion.",
  ],
  "lake-house": [
    "Dock portrait: family gathered on a wooden dock, lake reflections behind, relaxed summer posture.",
    "Canoe-side candid: family near a canoe or towels, one subject adjusting a life jacket, soft water light.",
    "Porch-lake frame: family on the lake-house porch, screen door and pine shadows, water visible beyond.",
    "Golden shoreline crop: tighter grouping at shore level, sparkling highlights and breezy hair.",
  ],
  "slim-aarons": [
    "Poolside loungers: family arranged beside a glamorous pool, crisp resort geometry and sunlit leisure.",
    "Terrace cocktail frame: family on a tiled terrace with mid-century furniture, relaxed elegant poses.",
    "Wide estate composition: family small in a luxurious architectural setting, pool and palms leading the eye.",
    "Close resort portrait: tighter grouping with sunglasses, towels and saturated vacation color.",
  ],
  "y2k-disposable": [
    "Party-kitchen flash: family squeezed around a kitchen counter, harsh flash, casual early-2000s clutter.",
    "Basement-couch frame: family on a low couch, off-center crop, motion blur and date-stamp energy.",
    "Hallway snapshot: family in a doorway or hall, direct flash and awkward candid timing.",
    "Table-game candid: family around a table mid-game or snack moment, plastic cups and flash reflections.",
  ],
  "coastal-grandmother": [
    "Porch-linen portrait: family on a shingled porch in soft linens, hydrangeas and sea air.",
    "Kitchen-island candid: family gathered around a bright coastal kitchen island, calm gestures and ceramics.",
    "Beach-path stroll: family walking a sandy path through beach grass, gentle wind and pale palette.",
    "Window-seat close-up: tighter soft portrait near white curtains, woven textures and warm quiet.",
  ],
  "amalfi-summer": [
    "Lemon-terrace frame: family on a tiled terrace with lemons and sea behind, sunlit Italian color.",
    "Stairway candid: family moving along whitewashed steps, one turning back, flowers and railings framing.",
    "Cafe-balcony portrait: family around a small table overlooking the coast, relaxed vacation elegance.",
    "Wide cliffside view: family small against pastel buildings and blue water, postcard composition.",
  ],
  "70s-station-wagon": [
    "Driveway departure: family beside a wood-paneled station wagon, luggage and warm late-afternoon haze.",
    "Open-tailgate candid: family gathered around the open tailgate, snacks and blankets visible.",
    "Roadside snapshot: family stopped at a scenic pullout, retro wardrobe and imperfect film framing.",
    "Front-seat close frame: tighter through-window composition with faces layered behind glass reflections.",
  ],
  "royal-family-portrait": [
    "Palace settee state portrait: selected cast arranged around a carved velvet settee, one seated anchor and others standing in a triangular court-portrait composition, gilded frames and marble floor visible.",
    "Gallery procession frame: selected cast walking slowly through a long gilded palace corridor, full regalia and cape hems visible, one subject glancing toward another, portraits and chandeliers receding behind.",
    "Balcony proclamation portrait: selected cast gathered at a stone balcony rail with velvet drapes and columns, waist-up to knee-up crop, hands resting naturally on the rail, palace garden softly beyond.",
    "Candlelit crown close-up: tighter dignified portrait near candelabra and dark oil paintings, faces and embroidered details prominent, layered shoulders and jewelry replacing the standard full-room group setup.",
  ],
  "disney-world": [
    "Castle-plaza arrival: selected cast full-body on warm stone pavers near flowerbeds and banners, colorful vacation outfits, snacks or balloons in hand, fantasy castle silhouette centered softly behind.",
    "Parade-curb candid: selected cast sitting or leaning along a cheerful parade curb, one child waving toward off-frame activity, lanterns and festive bunting around them, no characters or logos.",
    "Fireworks-night portrait: waist-up close grouping with glowing castle lights and soft fireworks bokeh behind, relaxed after-dark vacation smiles, ears and snack details visible without branding.",
    "Garden-walk wide frame: selected cast walking across a landscaped castle garden path, flowerbeds and decorative bridges leading the eye, wider environment and sky giving the vacation scene scale.",
  ],
  "national-park": [
    "Granite-overlook hero: selected cast standing full-body on a safe marked overlook, pine forest and granite cliffs sweeping behind, day packs and trail layers visible.",
    "Trail-map candid: selected cast paused on a winding pine trail around a folded map or water bottle, asymmetrical spacing, visible hands, boots and meadow grass foreground.",
    "Log-bench rest portrait: selected cast seated or leaning on a fallen log near wildflowers, knee-up crop, soft cliff and forest layers behind, one small backpack or leash detail anchoring the frame.",
    "Waterfall-mist close crop: tighter portrait beside a misty falls or bright alpine stream, faces and fleece textures prominent, cliffs and evergreens compressed into a soft background.",
  ],
  "hawaii-vacation": [
    "Lava-rock shoreline portrait: selected cast full-body near black lava rock and gentle surf, barefoot on wet sand, palms and volcanic hills layered in the sunset background.",
    "Palm-path stroll: selected cast walking along a beach path under palms, leis and linen moving in the breeze, asymmetrical spacing with plumeria and sand in the foreground.",
    "Beach-blanket candid: selected cast seated or kneeling around a simple island picnic blanket, plumeria and woven textures nearby, ocean glow and lava rocks framing the edge.",
    "Ocean-breeze close-up: tighter shoulder-to-waist portrait with flowers and palms framing faces, wind-softened hair and white linen details, turquoise water blurred behind.",
  ],
  "cape-cod-summer": [
    "Dune-path family portrait: selected cast standing full-body along a sandy dune path, hydrangeas and weathered cedar cottage behind, white fence and calm water glimpse visible.",
    "Shingled-porch morning: selected cast seated or leaning on cedar-shingle cottage steps, navy stripes and cream layers, hydrangea pots and screen door framing a quiet medium crop.",
    "Beach-blanket candid: selected cast gathered on a striped blanket near dune grass, one subject reaching for a tote or shell, low relaxed camera with pale sand foreground.",
    "Hydrangea-fence close crop: tighter coastal portrait beside blue hydrangeas and a white fence, faces and linen textures prominent, cottage shingles and sea haze softly compressed.",
  ],
  "pixar-family": [
    "Hero family pose: full group in a bright expressive stance, clear silhouettes and warm animated faces.",
    "Kitchen chaos frame: family mid-action in a playful domestic setting, exaggerated gestures and cinematic color.",
    "Close emotion beat: tighter character-focused composition with big eyes, soft smiles and tactile details.",
    "Wide world frame: family placed in a richly designed environment with depth, props and storybook staging.",
  ],
  "manga-family": [
    "Dynamic lineup panel: family in a confident manga composition with speed-line energy and varied poses.",
    "Quiet slice-of-life frame: family gathered in a soft everyday setting, expressive eyes and gentle gestures.",
    "Low-angle hero crop: family framed dramatically from below, hair and clothing catching stylized motion.",
    "Wide establishing panel: family placed in an atmospheric environment with strong graphic silhouettes.",
  ],
  "superhero-family": [
    "Rooftop hero lineup: family centered against skyline, capes and costumes reading clearly in golden rim light.",
    "Action-ready stance: family staggered as if about to leap forward, dramatic low angle and lens flare.",
    "Close team portrait: tighter grouping with confident expressions, costume textures and cinematic haze.",
    "Wide skyline poster: family small but powerful on rooftop edge, city and sunset carrying scale.",
  ],
  "saturday-morning": [
    "Breakfast chaos cel: family around the kitchen table, cereal and gestures frozen in bright cartoon timing.",
    "Living-room gag frame: family posed in a cheerful animated room, broad expressions and clear outlines.",
    "Doorway entrance beat: family bursting through or gathering in a doorway, exaggerated motion arcs.",
    "Wide sitcom tableau: full-room cartoon composition with props, primary colors and playful spacing.",
  ],
  "ghibli-countryside": [
    "Tall-grass breeze: family standing in wind-blown grass, one small gesture, huge soft sky.",
    "Pathway stroll: family walking along a dirt path toward a solitary tree, warm painted afternoon.",
    "Hilltop pause: family gathered on a rise looking outward, clouds and landscape carrying wonder.",
    "Close pastoral portrait: tighter grouping with grass and flowers in foreground, gentle hand-painted warmth.",
  ],
  "renaissance-oil": [
    "Seated candle tableau: family arranged around a table, hands and faces lit in classical chiaroscuro.",
    "Standing noble portrait: family staggered in a painterly triangular composition, rich fabric and deep shadows.",
    "Intimate close crop: faces emerging from dark background, warm candle edge and old-master stillness.",
    "Wide studio scene: family placed within a sparse period interior, props guiding the eye like an oil painting.",
  ],
  "yellow-cartoon": [
    "Couch-gag lineup: family on a living-room couch, simplified features and broad broadcast expressions.",
    "Kitchen gag frame: family around a cartoon kitchen table, simple props and bright flat color.",
    "Doorway gag pose: family stacked in a doorway or hallway, everyone facing camera with exaggerated reactions.",
    "Wide living-room cel: full room visible with family centered, flat shadows and classic TV composition.",
  ],
  "lego-family": [
    "Brick-base portrait: minifigure family standing on a clean brick base, accessories arranged around them.",
    "Mini porch set: family posed in a tiny brick-built porch scene, macro lens and glossy plastic highlights.",
    "Play-table frame: wider product-photo setup showing the brick set on a table, shallow depth of field.",
    "Close minifigure crop: tighter character grouping with printed smiles, C-shaped hands and plastic texture.",
  ],
  "watercolor-storybook": [
    "Garden path page: family walking along a whimsical path, soft washes and lantern flowers.",
    "Cottage foreground: family gathered near a distant cottage, foreground petals and warm windows.",
    "Close illustrated portrait: tighter hand-painted family grouping with delicate ink and paper grain.",
    "Wide storybook spread: family small in a magical garden landscape, path leading through the scene.",
  ],
  "spirited-away": [
    "Bridge lantern frame: family on ornate bridge with lanterns rising, soft steam and twilight glow.",
    "Bath-house wide shot: family smaller against glowing architecture, indigo sky and red lantern rhythm.",
    "Close wonder portrait: family faces lit by lantern glow, one hand reaching toward drifting paper light.",
    "Steam-lane candid: family moving through a misty lantern street, warm and cool washes layered.",
  ],
  "south-park": [
    "Sidewalk lineup: family in chunky winter coats on snowy street, flat cutout shapes and deadpan expressions.",
    "Bus-stop frame: family gathered near a simple school-bus or sign, broad horizontal TV composition.",
    "Snowfall wide shot: family small in a flat mountain-town scene, bright cut paper against pale snow.",
    "Close cutout portrait: tighter group with round eyes and simple mouths, visible paper texture.",
  ],
  "the-sims": [
    "Living-room gameplay: family in a Sims living room with plumbobs, three-quarter overhead camera.",
    "Kitchen interaction: family mid-Sim gesture around a kitchen island, bright game-rendered interior.",
    "Build-mode wide frame: family placed in a fully furnished room, more architecture visible.",
    "Close avatar portrait: tighter render focused on Sim faces, gestures and glossy Maxis materials.",
  ],
  "norman-rockwell": [
    "Kitchen-table story: family around a table in a warm narrative moment, hands and expressions leading.",
    "Porch-swing frame: family crowded onto a porch swing, wholesome mid-century charm and golden glow.",
    "Holiday-prep candid: family caught in a small domestic task, idealized gesture and warm oil texture.",
    "Cover-style portrait: vertical-feeling centered composition with foreground prop and Saturday-cover polish.",
  ],
  minecraft: [
    "Voxel lineup: family as blocky characters on grassy plains, items held clearly and village behind.",
    "House-front frame: family outside a player-built house, cubic trees and bright overworld sky.",
    "Adventure pose: family staggered as if starting a quest, tools and blocks creating foreground interest.",
    "Wide biome shot: family small against hills, clouds and blocky landscape, third-person camera energy.",
  ],
  "aardman-claymation": [
    "Tea-table frame: family holding teacups in a cozy cottage, visible clay fingerprints and warm grins.",
    "Kitchen contraption candid: family near a stove or model-train shelf, expressive eyebrows and comic clutter.",
    "Close clay portrait: tighter grouping with thumbprint texture, oversized teeth and sculpted shadows.",
    "Wide miniature set: family placed in hand-built cottage interior, props and warm practical light visible.",
  ],
  "card-easter": [
    "Tulip-walk card: selected cast walking through tulips, airy negative space low-right for greeting text.",
    "Garden-bench card: selected cast gathered near a bench with blossoms behind, soft pastel text area.",
    "Basket candid card: selected cast with a small woven basket detail, greeting space in bright garden ground.",
    "Close spring portrait: waist-up grouping framed by tulips and blossoms, clean serif-card negative space.",
  ],
  "card-diwali": [
    "Rangoli-side card: selected cast gathered beside bright rangoli, greeting space upper-left among soft lights.",
    "Diya-light portrait: tighter selected-cast grouping lit by diyas, marigolds framing a clean text area.",
    "Festive doorway card: selected cast in elegant clothing near garlands and string lights, balanced greeting space.",
    "Table-candid card: selected cast placing or holding a diya, warm gold text zone opposite action.",
  ],
  "card-eid": [
    "Courtyard greeting card: selected cast gathered in bright courtyard, lanterns and flowers with upper-left text space.",
    "Sweets-table candid: selected cast holding sweets near dates and flowers, placed opposite a clean greeting area.",
    "Morning portrait card: tighter elegant grouping after prayers, soft airy background reserved for text.",
    "Lantern-frame card: selected cast framed by textiles and lanterns, refined negative space above.",
  ],
  "card-nowruz": [
    "Haft-sin side card: selected cast beside a bright haft-sin table, mirror and candles catching light, clean greeting space upper-left.",
    "Poetry-book portrait: tighter selected-cast grouping near hyacinths and a Hafez or Shahnameh-style poetry book, soft negative space above.",
    "Spring doorway card: selected cast standing near a sunlit doorway with sabzeh, painted eggs and flowers in the foreground, greeting space to one side.",
    "Wide Nowruz table card: selected cast smaller behind or beside the haft-sin table, apples, sprouts, painted eggs, mirror and candles visible, calm readable greeting zone.",
  ],
  "card-dia-de-muertos": [
    "Ofrenda-side card: selected cast beside glowing ofrenda, marigold path leading to top-left greeting space.",
    "Candle portrait card: tighter selected-cast grouping with one candle gesture, respectful text area in warm shadow.",
    "Papel-picado frame: selected cast foreground right, colorful papel picado above creating a readable greeting zone.",
    "Marigold candid card: selected cast placing or holding marigolds, reverent negative space opposite.",
  ],
  "card-birthday": [
    "Cake-blow card: selected cast around lit cake, birthday greeting space upper-left.",
    "Streamer portrait: selected cast grouped beneath streamers and pompoms, clean text area in bright wall space.",
    "Gift-table candid: selected cast around gifts and plates, text balanced in open background.",
    "Close candle crop: tighter faces around candle glow, soft party details framing readable type.",
  ],
  "card-luxury-carved-number-birthday": [
    "Carved-number breakthrough poster: selected birthday subject centered inside a large birthday-age number cut into an off-white textured paper wall, face and shoulder extending outside the number, soft blue balloons and white florals inside, tasteful wall typography from the provided card text only.",
    "Bouquet-and-balloon number card: selected cast tucked into the deep carved birthday number with realistic inner shadows, elegant bouquet on one side, one hand or foot breaking the number edge for 3D depth, clean luxury wall negative space for exact user text.",
    "Minimal magazine cover poster: oversized carved birthday-age number dominates the frame, natural laughter in dark denim or premium casual styling, warm side sunlight, subtle rim light, serif typography on the wall using supplied text, no sample names or sample ages.",
    "Close luxury paper-wall crop: tight vertical poster framing on the carved number opening, premium off-white texture, soft palette-matched balloons and white flowers, realistic shadows under extended limbs, natural colors, no tree shadows and no fake lighting.",
  ],
  "card-anniversary": [
    "Champagne-toast card: selected cast close together near a small table with champagne or sparkling glasses, greeting space upper-right.",
    "Garden-terrace portrait: selected cast standing or seated among cream florals and candles, soft negative space on the left.",
    "Close tender card: selected cast in a tighter affectionate crop with hands or shoulders close, flowers framing readable greeting text.",
    "Wide romantic scene: selected cast smaller in the lower third on a candlelit terrace or dining nook, large calm text area above.",
  ],
  "card-halloween": [
    "Porch-steps card: selected cast in gentle costumes on steps, greeting space on the right.",
    "Pumpkin-light portrait: tighter grouping lit from below by jack-o-lanterns, clean dusk text area.",
    "Doorway-costume card: selected cast framed by porch door and wheat wreath, text in foggy side space.",
    "Wide porch scene: pumpkins leading foreground, selected cast off-center, spooky-soft negative space above.",
  ],
  "card-thanksgiving": [
    "Harvest-table card: selected cast around long table, upper-right greeting space in warm background.",
    "Dish-passing candid: selected cast passing or holding a dish, text area balanced above.",
    "Window-light portrait: tighter selected-cast grouping beside autumn table, soft blank wall or window space for greeting.",
    "Wide dining scene: full spread visible with selected cast off-center, calm card text zone overhead.",
  ],
  "card-new-years": [
    "Midnight-toast card: selected cast raising coupes or glasses, confetti above with clean year/greeting space.",
    "Chandelier portrait: tighter glam grouping under warm chandelier, serif text area in dark bokeh.",
    "Confetti-candid card: selected cast through falling gold confetti, placed opposite text.",
    "Wide party frame: elegant room and glass highlights visible, selected cast centered low with greeting above.",
  ],
  "card-graduation": [
    "Tassel-adjust card: parent adjusting graduate's tassel, negative space upper-right for name and date.",
    "Brick-wall portrait: selected cast around graduate or solo graduate against ivy brick, dignified text zone to one side.",
    "Cap-toss candid: selected cast with subtle cap motion, clean sky or wall space for text.",
    "Bench-side card: graduate seated or standing near bench, warm academic framing.",
  ],
  "card-newborn": [
    "Bedside announcement: selected cast gathered on white bedding with newborn center when selected, name/date space above.",
    "Overhead tender frame: slightly high angle on selected cast and soft bedding details, airy text zone.",
    "Window-light portrait: selected cast near soft curtains, clean negative space.",
    "Basket-detail card: selected cast with folded blankets and muslin details, delicate text area.",
  ],
  "card-save-the-date": [
    "Meadow-walk card: selected cast walking through meadow, date space lower-right.",
    "Temple-to-temple portrait: intimate close grouping with golden backlight, names/date in soft field space.",
    "Fence-side candid: selected cast near split-rail fence, clean text opposite.",
    "Wide golden meadow: small figures in romantic landscape, airy lower-right card typography zone.",
  ],
  "card-mothers-day": [
    "Close bouquet portrait: selected cast shown waist-up near the lower-left third, holding one bouquet low in frame, face clear, large clean greeting space upper-right.",
    "Standing wisteria card: selected cast standing or walking under the wisteria trellis, hands relaxed or holding one single flower, no large bouquet, greeting space on the left.",
    "Garden-bench card: selected cast seated or leaning beside a garden bench, flowers resting on the bench or foreground instead of held in both hands, greeting space above.",
    "Wide spring garden card: selected cast smaller in the lower third among blooms with trellis behind, mostly environment and clean pastel negative space for text.",
  ],
  "card-fathers-day": [
    "Backyard-catch card: father tossing baseball with children, greeting space upper-left.",
    "Shoulder-lift portrait: selected cast in warm affectionate pose, blank sky or foliage text area.",
    "Fence-side candid: selected cast near bicycle and fence, dappled light, balanced text zone.",
    "Close denim portrait: tighter grouping in chambray and denim, soft backyard details around greeting space.",
  ],
  "card-lunar-new-year": [
    "Round-table card: selected cast gathered around dumplings and tea, upper-left greeting space.",
    "Red-envelope candid: selected cast holding a red envelope, lanterns framing text area.",
    "Lantern portrait: tighter selected-cast grouping in red-and-gold wardrobe, clean warm background for greeting.",
    "Wide festive interior: altar oranges and lanterns visible, selected cast off-center with bilingual text zone.",
  ],
  "card-hanukkah": [
    "Menorah-light card: selected cast around glowing menorah, upper-right greeting space in cool window area.",
    "Shamash candid: one subject lighting candle, family leaning in, readable text zone opposite flame.",
    "Window-snow portrait: tighter selected-cast grouping beside snowy window and menorah, warm-cool card balance.",
    "Table-detail card: latkes, gelt and menorah foreground, selected cast behind with calm greeting space above.",
  ],
} satisfies Partial<Record<string, ThemeVariationPrompts>>;

const CATEGORY_VARIATIONS = {
  photoreal: [
    "Environmental hero proof: polished environmental portrait, natural spacing, strong setting context, clear faces.",
    "Anchored portrait proof: selected cast held in a still seated, leaning or clustered arrangement, one meaningful prop or setting edge framing them.",
    "Candid story proof: selected cast in one clear action beat within the same setting, visible hands or feet when natural, asymmetrical spacing.",
    "Face-led editorial proof: intimate emotional portrait focused on faces, hands, and one clean negative-space field.",
  ],
  stylized: [
    "World hero proof: selected cast using the theme's signature visual language, clear silhouettes, expressive poses and visible environment.",
    "Character portrait proof: readable faces, stronger expressions and one foreground prop or design detail.",
    "Action story proof: selected cast in a clear gesture or interaction, asymmetrical spacing, dynamic camera height and energetic staging.",
    "World proof: more of the themed environment around the selected cast without changing the concept.",
  ],
  card: [
    "Close greeting card proof: selected cast placed low or to one side, faces readable, generous clean negative space reserved for the greeting.",
    "Standing greeting card proof: selected cast standing or walking in the occasion setting, text area balanced opposite them.",
    "Anchored greeting card proof: selected cast seated or leaning near a clear prop, doorway, bench, table or floral frame, medium crop and readable faces.",
    "Environmental greeting card proof: selected cast in the lower third, foreground details and occasion environment visible, calm readable greeting zone.",
  ],
} satisfies Record<string, ThemeVariationPrompts>;

export function getThemeVariationPrompts(
  themeId: string,
  category: keyof typeof CATEGORY_VARIATIONS,
): ThemeVariationPrompts {
  return THEME_VARIATION_PROMPTS[themeId] ?? CATEGORY_VARIATIONS[category];
}
