export type ThemeVariationPrompts = readonly [string, string, string, string];

export const THEME_VARIATION_PROMPTS: Partial<Record<string, ThemeVariationPrompts>> = {
  "golden-hour-beach": [
    "Walking shoreline frame: family barefoot on wet reflective sand, staggered naturally, one person glancing back, ocean horizon clean and low.",
    "Seated dunes frame: family nestled near sea oats on a blanket, relaxed shoulder-to-shoulder grouping, warm rim light through grasses.",
    "Tide-play candid: family gathered at the waterline with small splashes and rolled cuffs, laughter caught mid-motion, beach stretching behind.",
    "Quiet portrait frame: tighter waist-up grouping with wind in hair and linen, sunset glow behind shoulders, soft negative space of sky and sea.",
  ],
  "autumn-cabin": [
    "Cabin-steps welcome: family gathered on wooden porch steps with mugs and knit layers, breath visible, pumpkins and boots nearby.",
    "Woodpile candid: family near stacked firewood, one subject adjusting a scarf, leaves drifting through crisp morning light.",
    "Trail-return moment: family walking back toward the cabin along a leaf-strewn path, casual spacing and warm hand gestures.",
    "Window-glow portrait: tighter grouping beside the cabin window with amber interior light, blankets wrapped around shoulders.",
  ],
  "kinfolk-kitchen": [
    "Table-prep frame: family around a flour-dusted table, hands arranging ingredients, one subject leaning in with a small laugh.",
    "Sink-window portrait: family gathered near the kitchen window, herb pots and ceramic mugs visible, quiet editorial stillness.",
    "Shared-platter candid: family passing a wooden board or bowl across the table, overlapping hands and natural eye contact.",
    "Doorway crop: tighter vertical-feeling composition through a kitchen doorway, linen textures, soft side light and calm expressions.",
  ],
  "vintage-polaroid": [
    "Couch-squeeze snapshot: family packed close on the living-room couch, flash-lit faces, one person slightly cropped by the Polaroid edge.",
    "Kitchen-counter snapshot: family leaning around a laminate counter with mugs or snacks, off-level framing and casual mid-laugh timing.",
    "Hallway-flash frame: family clustered in a narrow hallway or doorway, direct flash, red-eye-era imperfection, warm paneling behind.",
    "Floor-level candid: family sitting on carpet around scattered albums or toys, low awkward camera angle, one subject blurred by motion.",
  ],
  "leibovitz-studio": [
    "Classical seated tableau: family arranged around one seated anchor subject, painterly triangular composition and controlled gestures.",
    "Standing editorial frame: staggered standing group with tailored silhouettes, one subject slightly turned away, dramatic side light.",
    "Close intimate crop: shoulder-to-shoulder grouping, faces layered in depth, quiet unscripted glances under Rembrandt light.",
    "Wide set portrait: family placed within the painted studio backdrop, polished floor visible, refined magazine-cover negative space.",
  ],
  "wes-anderson": [
    "Standing lineup proof: selected subject or cast standing full-body on the centered patterned rug, hands empty at sides, serious deadpan expression, perfectly symmetrical furniture around them.",
    "Seated tableau proof: selected subject or cast seated formally on a couch or bench, holding a single tiny teacup or flower stem, exact pastel order and balanced side tables.",
    "Doorway grid proof: selected subject or cast standing rigidly inside nested rectangular doorways or wall panels, no handheld prop, dollhouse precision.",
    "Wide room proof: selected subject or cast placed small in a wider symmetrical room, full rug and centered furniture visible, hands folded or at sides, no book.",
  ],
  "christmas-morning": [
    "Tree-side floor candid: family clustered on the rug beside the glowing tree, wrapping paper in foreground, cocoa mugs in hand.",
    "Couch-and-stockings frame: family squeezed on the couch under stockings and garland, one subject mid-laugh over an opened gift.",
    "Morning-window portrait: tighter warm pajama grouping with tree bokeh behind and cool window fill from one side.",
    "Present-opening action: family leaning into a shared present reveal, hands overlapping, ribbon and paper creating lively foreground.",
  ],
  "card-christmas": [
    "Front-step hero card: selected cast on the porch steps beside the wreath, clean negative space on the left for greeting text.",
    "Doorway glow card: selected cast gathered in the open doorway, warm interior light behind, snow and pines framing the edges.",
    "Porch-rail candid card: selected cast leaning naturally along the porch rail, one subject mid-laugh when more than one is selected, greeting space in snowy sky.",
    "Tighter wreath portrait: waist-up grouping beside the lit wreath, elegant holiday wardrobe, calm serif-card negative space.",
  ],
  "national-geographic": [
    "Ridge-pause frame: family silhouetted against layered mountains, one adjusting a pack strap, strong documentary spacing.",
    "Trail-movement frame: family walking single-file across scree or tundra, wind shaping clothing, vast valley opening beside them.",
    "Map-check candid: family gathered around a folded map or thermos on the ridge, real weather and practical gestures.",
    "Wide awe portrait: family small against the dawn landscape, placed on the right third with dramatic sky and mist.",
  ],
  "film-noir": [
    "Desk-side mystery: family grouped around a heavy desk, one subject holding a sealed letter, venetian shadows cutting across faces.",
    "Window-silhouette frame: family near the blinds with hard backlight, elegant profiles and protective body language.",
    "Doorway noir tableau: staggered figures in a dim office doorway, one glancing over a shoulder, deep negative shadow.",
    "Close silver portrait: tight dramatic grouping with faces emerging from black, silk highlights and a single practical lamp.",
  ],
  "tuscan-summer": [
    "Long-table lunch: family gathered at a rustic outdoor table, linen, fruit and glasses catching hot afternoon light.",
    "Villa-walk frame: family walking along a cypress-lined path, relaxed spacing, terracotta walls and olive trees behind.",
    "Courtyard portrait: family in a shaded stone courtyard, one leaning on a chair, sun patches across the ground.",
    "Vineyard-wide frame: family placed against rolling vines and hills, golden haze and breezy summer wardrobe.",
  ],
  "cherry-blossom": [
    "Petal-path stroll: family walking slowly beneath blossoms, one subject looking up, petals crossing foreground.",
    "Bench portrait: family gathered near a garden bench, pastel canopy overhead, soft calm expressions.",
    "Bridge-frame candid: family paused on a small garden bridge, blossoms reflected below, asymmetric composition.",
    "Close blossom crop: tighter portrait with branches framing faces, delicate petals and airy negative space.",
  ],
  "snowy-hygge": [
    "Window-nook portrait: family wrapped in knits near a glowing window, snow falling outside, mugs and blankets visible.",
    "Cabin-floor candid: family seated around a low table or rug, warm lamplight and soft winter clutter.",
    "Doorway snow frame: family just inside the open cabin door, cool snow outside and warm interior spill behind them.",
    "Firelight close-up: tighter grouping near the hearth, faces warmed by flame, soft shadows and cozy textures.",
  ],
  "desert-santa-fe": [
    "Adobe-wall portrait: family arranged against sun-warmed adobe, turquoise and woven textures, sculptural shadows.",
    "Courtyard candid: family gathered around a tiled courtyard table, one passing a cup, desert plants framing edges.",
    "Wide mesa frame: family placed before distant desert mesas, low sun and long shadows across sand.",
    "Doorway textile crop: tighter composition in a carved doorway with rugs and pottery as rich foreground detail.",
  ],
  "parisian-cafe": [
    "Cafe-table candid: family around a small sidewalk table, cups and pastries, one subject mid-laugh.",
    "Awning portrait: family standing beneath striped awning, street reflections and wrought-iron detail behind.",
    "Window-seat frame: tighter grouping by a cafe window, warm interior glow and soft Paris street bokeh.",
    "Crosswalk lifestyle: family walking past the cafe frontage, motion in coats and scarves, cinematic street rhythm.",
  ],
  "new-york-city": [
    "Brownstone-step portrait: family on stoop steps, city texture behind, relaxed stacked composition.",
    "Crosswalk motion frame: family mid-stride across a quiet street, taxis and architecture softened in background.",
    "Corner-deli candid: family gathered near a neighborhood storefront, one subject turning back toward camera.",
    "Rooftop skyline portrait: family placed against distant skyline, wind and evening light shaping silhouettes.",
  ],
  "paris-family-stroll": [
    "Morning-walk frame: family walking along a limestone street, Eiffel Tower large but soft in background.",
    "Bridge pause: family leaning lightly along a Paris bridge rail, soft river light and elegant negative space.",
    "Cafe-corner pass: family passing a cafe corner with motion in coats, editorial travel framing.",
    "Tighter tower portrait: waist-up grouping with warm morning rim light and landmark geometry behind.",
  ],
  "backyard-picnic": [
    "Blanket-circle candid: family seated in a loose picnic circle, food in foreground and laughter crossing the blanket.",
    "Tree-shade portrait: family arranged under dappled leaves, lemonade glasses catching highlights.",
    "Serving moment: family passing strawberries or sandwiches, overlapping hands and relaxed expressions.",
    "Wide backyard frame: family small within garden beds, fence and soft flowers, sunny lifestyle atmosphere.",
  ],
  "sunday-sofa": [
    "Couch-squeeze frame: family tucked into blankets on the sofa, rain-lit window behind, book or mugs nearby.",
    "Window-light portrait: tighter grouping near the window with soft gray light and calm eye contact.",
    "Floor-and-sofa candid: some seated on the rug, some on the couch, lived-in Sunday clutter around them.",
    "Over-shoulder quiet frame: one subject reading or reaching across, family layered in soft domestic depth.",
  ],
  "orchard-picking": [
    "Ladder-and-baskets frame: family beneath fruit trees with baskets, one reaching upward, sun through leaves.",
    "Row-walk candid: family walking between orchard rows, staggered spacing and late-season color.",
    "Harvest-table portrait: family gathered around baskets on a rustic table, fruit in foreground.",
    "Wide orchard view: family framed by repeating tree rows, warm rural light and playful motion.",
  ],
  "lake-house": [
    "Dock portrait: family gathered on a wooden dock, lake reflections behind, relaxed summer posture.",
    "Canoe-side candid: family near a canoe or towels, one subject adjusting a life jacket, soft water light.",
    "Porch-lake frame: family on the lake-house porch, screen door and pine shadows, water visible beyond.",
    "Golden shoreline crop: tighter grouping at shore level, sparkling highlights and breezy hair.",
  ],
  "slim-aarons": [
    "Poolside loungers: family arranged beside a glamorous pool, crisp resort geometry and sunlit leisure.",
    "Terrace cocktail frame: family on a tiled terrace with mid-century furniture, relaxed elegant poses.",
    "Wide estate composition: family small in a luxurious architectural setting, pool and palms leading the eye.",
    "Close resort portrait: tighter grouping with sunglasses, towels and saturated vacation color.",
  ],
  "y2k-disposable": [
    "Party-kitchen flash: family squeezed around a kitchen counter, harsh flash, casual early-2000s clutter.",
    "Basement-couch frame: family on a low couch, off-center crop, motion blur and date-stamp energy.",
    "Hallway snapshot: family in a doorway or hall, direct flash and awkward candid timing.",
    "Table-game candid: family around a table mid-game or snack moment, plastic cups and flash reflections.",
  ],
  "coastal-grandmother": [
    "Porch-linen portrait: family on a shingled porch in soft linens, hydrangeas and sea air.",
    "Kitchen-island candid: family gathered around a bright coastal kitchen island, calm gestures and ceramics.",
    "Beach-path stroll: family walking a sandy path through beach grass, gentle wind and pale palette.",
    "Window-seat close-up: tighter soft portrait near white curtains, woven textures and warm quiet.",
  ],
  "amalfi-summer": [
    "Lemon-terrace frame: family on a tiled terrace with lemons and sea behind, sunlit Italian color.",
    "Stairway candid: family moving along whitewashed steps, one turning back, flowers and railings framing.",
    "Cafe-balcony portrait: family around a small table overlooking the coast, relaxed vacation elegance.",
    "Wide cliffside view: family small against pastel buildings and blue water, postcard composition.",
  ],
  "70s-station-wagon": [
    "Driveway departure: family beside a wood-paneled station wagon, luggage and warm late-afternoon haze.",
    "Open-tailgate candid: family gathered around the open tailgate, snacks and blankets visible.",
    "Roadside snapshot: family stopped at a scenic pullout, retro wardrobe and imperfect film framing.",
    "Front-seat close frame: tighter through-window composition with faces layered behind glass reflections.",
  ],
  "pixar-family": [
    "Hero family pose: full group in a bright expressive stance, clear silhouettes and warm animated faces.",
    "Kitchen chaos frame: family mid-action in a playful domestic setting, exaggerated gestures and cinematic color.",
    "Close emotion beat: tighter character-focused composition with big eyes, soft smiles and tactile details.",
    "Wide world frame: family placed in a richly designed environment with depth, props and storybook staging.",
  ],
  "manga-family": [
    "Dynamic lineup panel: family in a confident manga composition with speed-line energy and varied poses.",
    "Quiet slice-of-life frame: family gathered in a soft everyday setting, expressive eyes and gentle gestures.",
    "Low-angle hero crop: family framed dramatically from below, hair and clothing catching stylized motion.",
    "Wide establishing panel: family placed in an atmospheric environment with strong graphic silhouettes.",
  ],
  "superhero-family": [
    "Rooftop hero lineup: family centered against skyline, capes and costumes reading clearly in golden rim light.",
    "Action-ready stance: family staggered as if about to leap forward, dramatic low angle and lens flare.",
    "Close team portrait: tighter grouping with confident expressions, costume textures and cinematic haze.",
    "Wide skyline poster: family small but powerful on rooftop edge, city and sunset carrying scale.",
  ],
  "saturday-morning": [
    "Breakfast chaos cel: family around the kitchen table, cereal and gestures frozen in bright cartoon timing.",
    "Living-room gag frame: family posed in a cheerful animated room, broad expressions and clear outlines.",
    "Doorway entrance beat: family bursting through or gathering in a doorway, exaggerated motion arcs.",
    "Wide sitcom tableau: full-room cartoon composition with props, primary colors and playful spacing.",
  ],
  "ghibli-countryside": [
    "Tall-grass breeze: family standing in wind-blown grass, one small gesture, huge soft sky.",
    "Pathway stroll: family walking along a dirt path toward a solitary tree, warm painted afternoon.",
    "Hilltop pause: family gathered on a rise looking outward, clouds and landscape carrying wonder.",
    "Close pastoral portrait: tighter grouping with grass and flowers in foreground, gentle hand-painted warmth.",
  ],
  "renaissance-oil": [
    "Seated candle tableau: family arranged around a table, hands and faces lit in classical chiaroscuro.",
    "Standing noble portrait: family staggered in a painterly triangular composition, rich fabric and deep shadows.",
    "Intimate close crop: faces emerging from dark background, warm candle edge and old-master stillness.",
    "Wide studio scene: family placed within a sparse period interior, props guiding the eye like an oil painting.",
  ],
  "yellow-cartoon": [
    "Couch-gag lineup: family on a living-room couch, simplified features and broad broadcast expressions.",
    "Kitchen gag frame: family around a cartoon kitchen table, simple props and bright flat color.",
    "Doorway gag pose: family stacked in a doorway or hallway, everyone facing camera with exaggerated reactions.",
    "Wide living-room cel: full room visible with family centered, flat shadows and classic TV composition.",
  ],
  "lego-family": [
    "Brick-base portrait: minifigure family standing on a clean brick base, accessories arranged around them.",
    "Mini porch set: family posed in a tiny brick-built porch scene, macro lens and glossy plastic highlights.",
    "Play-table frame: wider product-photo setup showing the brick set on a table, shallow depth of field.",
    "Close minifigure crop: tighter character grouping with printed smiles, C-shaped hands and plastic texture.",
  ],
  "watercolor-storybook": [
    "Garden path page: family walking along a whimsical path, soft washes and lantern flowers.",
    "Cottage foreground: family gathered near a distant cottage, foreground petals and warm windows.",
    "Close illustrated portrait: tighter hand-painted family grouping with delicate ink and paper grain.",
    "Wide storybook spread: family small in a magical garden landscape, path leading through the scene.",
  ],
  "spirited-away": [
    "Bridge lantern frame: family on ornate bridge with lanterns rising, soft steam and twilight glow.",
    "Bath-house wide shot: family smaller against glowing architecture, indigo sky and red lantern rhythm.",
    "Close wonder portrait: family faces lit by lantern glow, one hand reaching toward drifting paper light.",
    "Steam-lane candid: family moving through a misty lantern street, warm and cool washes layered.",
  ],
  "south-park": [
    "Sidewalk lineup: family in chunky winter coats on snowy street, flat cutout shapes and deadpan expressions.",
    "Bus-stop frame: family gathered near a simple school-bus or sign, broad horizontal TV composition.",
    "Snowfall wide shot: family small in a flat mountain-town scene, bright cut paper against pale snow.",
    "Close cutout portrait: tighter group with round eyes and simple mouths, visible paper texture.",
  ],
  "the-sims": [
    "Living-room gameplay: family in a Sims living room with plumbobs, three-quarter overhead camera.",
    "Kitchen interaction: family mid-Sim gesture around a kitchen island, bright game-rendered interior.",
    "Build-mode wide frame: family placed in a fully furnished room, more architecture visible.",
    "Close avatar portrait: tighter render focused on Sim faces, gestures and glossy Maxis materials.",
  ],
  "norman-rockwell": [
    "Kitchen-table story: family around a table in a warm narrative moment, hands and expressions leading.",
    "Porch-swing frame: family crowded onto a porch swing, wholesome mid-century charm and golden glow.",
    "Holiday-prep candid: family caught in a small domestic task, idealized gesture and warm oil texture.",
    "Cover-style portrait: vertical-feeling centered composition with foreground prop and Saturday-cover polish.",
  ],
  minecraft: [
    "Voxel lineup: family as blocky characters on grassy plains, items held clearly and village behind.",
    "House-front frame: family outside a player-built house, cubic trees and bright overworld sky.",
    "Adventure pose: family staggered as if starting a quest, tools and blocks creating foreground interest.",
    "Wide biome shot: family small against hills, clouds and blocky landscape, third-person camera energy.",
  ],
  "aardman-claymation": [
    "Tea-table frame: family holding teacups in a cozy cottage, visible clay fingerprints and warm grins.",
    "Kitchen contraption candid: family near a stove or model-train shelf, expressive eyebrows and comic clutter.",
    "Close clay portrait: tighter grouping with thumbprint texture, oversized teeth and sculpted shadows.",
    "Wide miniature set: family placed in hand-built cottage interior, props and warm practical light visible.",
  ],
  "card-easter": [
    "Tulip-walk card: selected cast walking through tulips, airy negative space low-right for greeting text.",
    "Garden-bench card: selected cast gathered near a bench with blossoms behind, soft pastel text area.",
    "Basket candid card: selected cast with a small woven basket detail, greeting space in bright garden ground.",
    "Close spring portrait: waist-up grouping framed by tulips and blossoms, clean serif-card negative space.",
  ],
  "card-diwali": [
    "Rangoli-side card: selected cast gathered beside bright rangoli, greeting space upper-left among soft lights.",
    "Diya-light portrait: tighter selected-cast grouping lit by diyas, marigolds framing a clean text area.",
    "Festive doorway card: selected cast in elegant clothing near garlands and string lights, balanced greeting space.",
    "Table-candid card: selected cast placing or holding a diya, warm gold text zone opposite action.",
  ],
  "card-eid": [
    "Courtyard greeting card: selected cast gathered in bright courtyard, lanterns and flowers with upper-left text space.",
    "Sweets-table candid: selected cast holding sweets near dates and flowers, placed opposite a clean greeting area.",
    "Morning portrait card: tighter elegant grouping after prayers, soft airy background reserved for text.",
    "Lantern-frame card: selected cast framed by textiles and lanterns, refined negative space above.",
  ],
  "card-dia-de-muertos": [
    "Ofrenda-side card: selected cast beside glowing ofrenda, marigold path leading to top-left greeting space.",
    "Candle portrait card: tighter selected-cast grouping with one candle gesture, respectful text area in warm shadow.",
    "Papel-picado frame: selected cast foreground right, colorful papel picado above creating a readable greeting zone.",
    "Marigold candid card: selected cast placing or holding marigolds, reverent negative space opposite.",
  ],
  "card-birthday": [
    "Cake-blow card: selected cast around lit cake, birthday greeting space upper-left.",
    "Streamer portrait: selected cast grouped beneath streamers and pompoms, clean text area in bright wall space.",
    "Gift-table candid: selected cast around gifts and plates, text balanced in open background.",
    "Close candle crop: tighter faces around candle glow, soft party details framing readable type.",
  ],
  "card-anniversary": [
    "Champagne-toast card: selected cast close together near a small table with champagne or sparkling glasses, greeting space upper-right.",
    "Garden-terrace portrait: selected cast standing or seated among cream florals and candles, soft negative space on the left.",
    "Close tender card: selected cast in a tighter affectionate crop with hands or shoulders close, flowers framing readable greeting text.",
    "Wide romantic scene: selected cast smaller in the lower third on a candlelit terrace or dining nook, large calm text area above.",
  ],
  "card-halloween": [
    "Porch-steps card: selected cast in gentle costumes on steps, greeting space on the right.",
    "Pumpkin-light portrait: tighter grouping lit from below by jack-o-lanterns, clean dusk text area.",
    "Doorway-costume card: selected cast framed by porch door and wheat wreath, text in foggy side space.",
    "Wide porch scene: pumpkins leading foreground, selected cast off-center, spooky-soft negative space above.",
  ],
  "card-thanksgiving": [
    "Harvest-table card: selected cast around long table, upper-right greeting space in warm background.",
    "Dish-passing candid: selected cast passing or holding a dish, text area balanced above.",
    "Window-light portrait: tighter selected-cast grouping beside autumn table, soft blank wall or window space for greeting.",
    "Wide dining scene: full spread visible with selected cast off-center, calm card text zone overhead.",
  ],
  "card-new-years": [
    "Midnight-toast card: selected cast raising coupes or glasses, confetti above with clean year/greeting space.",
    "Chandelier portrait: tighter glam grouping under warm chandelier, serif text area in dark bokeh.",
    "Confetti-candid card: selected cast through falling gold confetti, placed opposite text.",
    "Wide party frame: elegant room and glass highlights visible, selected cast centered low with greeting above.",
  ],
  "card-graduation": [
    "Tassel-adjust card: parent adjusting graduate's tassel, negative space upper-right for name and date.",
    "Brick-wall portrait: selected cast around graduate or solo graduate against ivy brick, dignified text zone to one side.",
    "Cap-toss candid: selected cast with subtle cap motion, clean sky or wall space for text.",
    "Bench-side card: graduate seated or standing near bench, warm academic framing.",
  ],
  "card-newborn": [
    "Bedside announcement: selected cast gathered on white bedding with newborn center when selected, name/date space above.",
    "Overhead tender frame: slightly high angle on selected cast and soft bedding details, airy text zone.",
    "Window-light portrait: selected cast near soft curtains, clean negative space.",
    "Basket-detail card: selected cast with folded blankets and muslin details, delicate text area.",
  ],
  "card-save-the-date": [
    "Meadow-walk card: selected cast walking through meadow, date space lower-right.",
    "Temple-to-temple portrait: intimate close grouping with golden backlight, names/date in soft field space.",
    "Fence-side candid: selected cast near split-rail fence, clean text opposite.",
    "Wide golden meadow: small figures in romantic landscape, airy lower-right card typography zone.",
  ],
  "card-mothers-day": [
    "Close bouquet portrait: selected cast shown waist-up near the lower-left third, holding one bouquet low in frame, face clear, large clean greeting space upper-right.",
    "Standing wisteria card: selected cast standing or walking under the wisteria trellis, hands relaxed or holding one single flower, no large bouquet, greeting space on the left.",
    "Garden-bench card: selected cast seated or leaning beside a garden bench, flowers resting on the bench or foreground instead of held in both hands, greeting space above.",
    "Wide spring garden card: selected cast smaller in the lower third among blooms with trellis behind, mostly environment and clean pastel negative space for text.",
  ],
  "card-fathers-day": [
    "Backyard-catch card: father tossing baseball with children, greeting space upper-left.",
    "Shoulder-lift portrait: selected cast in warm affectionate pose, blank sky or foliage text area.",
    "Fence-side candid: selected cast near bicycle and fence, dappled light, balanced text zone.",
    "Close denim portrait: tighter grouping in chambray and denim, soft backyard details around greeting space.",
  ],
  "card-lunar-new-year": [
    "Round-table card: selected cast gathered around dumplings and tea, upper-left greeting space.",
    "Red-envelope candid: selected cast holding a red envelope, lanterns framing text area.",
    "Lantern portrait: tighter selected-cast grouping in red-and-gold wardrobe, clean warm background for greeting.",
    "Wide festive interior: altar oranges and lanterns visible, selected cast off-center with bilingual text zone.",
  ],
  "card-hanukkah": [
    "Menorah-light card: selected cast around glowing menorah, upper-right greeting space in cool window area.",
    "Shamash candid: one subject lighting candle, family leaning in, readable text zone opposite flame.",
    "Window-snow portrait: tighter selected-cast grouping beside snowy window and menorah, warm-cool card balance.",
    "Table-detail card: latkes, gelt and menorah foreground, selected cast behind with calm greeting space above.",
  ],
} satisfies Partial<Record<string, ThemeVariationPrompts>>;

const CATEGORY_VARIATIONS = {
  photoreal: [
    "Hero proof: polished medium-wide portrait with natural spacing, strong face visibility and one subtle candid gesture.",
    "Candid proof: family mid-action within the same setting, overlapping hands or glances, photographed like an unforced keeper.",
    "Intimate proof: tighter emotional crop focused on faces, hands and eye contact while preserving the same light and wardrobe logic.",
    "Environmental proof: wider lifestyle frame with more of the location visible, family off-center and a distinctive foreground detail.",
  ],
  stylized: [
    "Hero proof: full-group frame using the theme's signature visual language, clear silhouettes and expressive poses.",
    "Character proof: closer family-focused frame with exaggerated gestures and readable faces in the same rendered style.",
    "World proof: wider frame showing more of the themed environment around the family without changing the concept.",
    "Alternate proof: different spacing, props, camera height and staging while preserving the same visual language.",
  ],
  card: [
    "Hero card proof: classic family portrait with generous clean negative space reserved for the greeting.",
    "Candid card proof: family interaction placed on one side of the frame, text area balanced opposite them.",
    "Intimate card proof: tighter emotional portrait with decorative details framing the readable text space.",
    "Environmental card proof: wider card composition with foreground details and a calm readable greeting zone.",
  ],
} satisfies Record<string, ThemeVariationPrompts>;

export function getThemeVariationPrompts(
  themeId: string,
  category: keyof typeof CATEGORY_VARIATIONS,
): ThemeVariationPrompts {
  return THEME_VARIATION_PROMPTS[themeId] ?? CATEGORY_VARIATIONS[category];
}
